export const uiConfig: { desktop: IUIConfig } = {
  desktop: {
    bottomBar: {
      position: 'absolute',
      bottom: 0,
      display: 'block',
      width: 1864,
    },
    infoButton: {
      position: 'absolute',
      bottom: 8,
      left: 48,
      display: 'block',
      width: 80,
      height: 80,
    },
    settingsButton: {
      position: 'absolute',
      bottom: 8,
      left: 160,
      display: 'block',
      width: 48,
      height: 48,
    },
    volumeButton: {
      position: 'absolute',
      bottom: 8,
      left: 240,
      display: 'block',
      width: 48,
      height: 48,
    },
    creditButton: {
      position: 'absolute',
      bottom: 8,
      left: 350,
      display: 'block',
      width: 224,
      height: 48,
    },
    middleSection: {
      position: 'absolute',
      bottom: 8,
      left: 610,
      display: 'block',
      width: 650,
      height: 56,
      marginBottom: 48,
    },
    betButton: {
      position: 'absolute',
      bottom: 8,
      left: 1280,
      display: 'block',

      width: 224,
      height: 48,
    },
    autoplayButton: {
      position: 'absolute',
      bottom: 8,
      left: 1530,
      display: 'block',
      height: 48,
      width: 128,
    },
    spinButton: {
      position: 'absolute',
      bottom: 8,
      left: 1660,
      display: 'block',
      height: 160,
      width: 160,
    },
  },
};
